/**
 * NIKATRU brand tokens - Style Dictionary v5 configuration.
 *
 * Two platforms are built from the same DTCG token sources (tokens/*.json):
 *
 *   css  -> build/tokens.css          CSS custom properties. Names mirror the live
 *                                     nikatru.com :root exactly (incl. --brand-ink),
 *                                     with dark values in a
 *                                     `@media (prefers-color-scheme: dark)` block.
 *   dart -> build/nikatru_tokens.dart Pure-Dart constants (imports only `dart:ui`,
 *                                     so it works in plain Dart and Flutter alike):
 *                                     NikatruTokens (light) + NikatruTokensDark.
 *
 * Custom formats are used (instead of the built-in `css/variables` /
 * `flutter/class.dart`) so that:
 *   - the CSS variable names match the live site byte-for-byte,
 *   - the dark palette ships as a prefers-color-scheme override block,
 *   - Dart colors use the `Color(0xFFRRGGBB)` form via `dart:ui`,
 *   - output carries no timestamps, keeping rebuilds byte-identical.
 */

/* --------------------------------------------------------------------- */
/* Canonical ordering - locked so output is deterministic and reviewable. */

const LIGHT_COLORS = [
  'ink', 'ink-2', 'primary', 'teal', 'bg', 'card', 'card-2',
  'text', 'strong', 'muted', 'line',
];
const DARK_COLORS = ['bg', 'card', 'card-2', 'text', 'strong', 'muted', 'line'];

const HEADER_CSS = `/**
 * NIKATRU brand tokens - generated by Style Dictionary. DO NOT EDIT BY HAND.
 * Edit packages/tokens/tokens/*.json and run \`npm run build\`.
 * Variable names intentionally mirror the live nikatru.com :root.
 */`;

const HEADER_DART = `// NIKATRU brand tokens - generated by Style Dictionary. DO NOT EDIT BY HAND.
// Edit packages/tokens/tokens/*.json and run \`npm run build\`.`;

/* ------------------------------------------------------------------ */
/* Helpers                                                            */

const raw = (token) => token.$value ?? token.value;

/** Collect one top-level token group into `name -> value` (path minus group, kebab-joined). */
function groupMap(dictionary, group) {
  const map = new Map();
  for (const token of dictionary.allTokens) {
    if (token.path[0] === group) map.set(token.path.slice(1).join('-'), raw(token));
  }
  return map;
}

/** Fail the build loudly if a required token disappears or is renamed. */
function must(map, key, group) {
  if (!map.has(key)) throw new Error(`[@nikatru/tokens] missing required token "${group}.${key}"`);
  return map.get(key);
}

/** Live-site CSS custom-property name for a color token. */
const cssVar = (name) => (name === 'ink' ? 'brand-ink' : name);

/** 'ink-2' -> 'ink2' (lowerCamelCase Dart identifier). */
const dartIdent = (name) => name.replace(/-+(.)/g, (_, c) => c.toUpperCase());

/** '#0B1220' -> 'Color(0xFF0B1220)' (dart:ui, fully opaque). */
function dartColor(hex) {
  const h = String(hex).replace('#', '').toUpperCase();
  if (!/^[0-9A-F]{6}$/.test(h)) {
    throw new Error(`[@nikatru/tokens] expected 6-digit hex color, got "${hex}"`);
  }
  return `Color(0xFF${h})`;
}

/** DTCG dimension -> CSS string ('16px' or {value:16, unit:'px'} -> '16px'). */
const dimToCss = (v) => (typeof v === 'object' && v !== null ? `${v.value}${v.unit}` : String(v));

/** DTCG dimension -> bare number string ('16px' -> '16'). */
const dimToNumber = (v) =>
  typeof v === 'object' && v !== null ? String(v.value) : String(v).replace(/px$/, '');

/* ------------------------------------------------------------------ */
/* Formats                                                            */

function formatCss({ dictionary }) {
  const light = groupMap(dictionary, 'color');
  const dark = groupMap(dictionary, 'dark');
  const font = groupMap(dictionary, 'font');
  const size = groupMap(dictionary, 'size');

  const lines = [HEADER_CSS, '', ':root {'];
  for (const name of LIGHT_COLORS) {
    lines.push(`  --${cssVar(name)}: ${must(light, name, 'color')};`);
  }
  lines.push(`  --radius: ${dimToCss(must(size, 'radius', 'size'))};`);
  lines.push(`  --font-display: "${must(font, 'display', 'font')}";`);
  lines.push(`  --font-body: "${must(font, 'body', 'font')}";`);
  lines.push('}', '', '@media (prefers-color-scheme: dark) {', '  :root {');
  for (const name of DARK_COLORS) {
    lines.push(`    --${cssVar(name)}: ${must(dark, name, 'dark')};`);
  }
  lines.push('  }', '}');
  return lines.join('\n') + '\n';
}

function formatDart({ dictionary }) {
  const light = groupMap(dictionary, 'color');
  const dark = groupMap(dictionary, 'dark');
  const font = groupMap(dictionary, 'font');
  const size = groupMap(dictionary, 'size');

  const radius = dimToNumber(must(size, 'radius', 'size'));

  const lines = [
    HEADER_DART,
    '',
    "import 'dart:ui' show Color;",
    '',
    '/// NIKATRU brand tokens - light palette (canonical values from nikatru.com).',
    'class NikatruTokens {',
    '  NikatruTokens._();',
    '',
  ];
  for (const name of LIGHT_COLORS) {
    lines.push(`  static const Color ${dartIdent(name)} = ${dartColor(must(light, name, 'color'))};`);
  }
  lines.push(
    '',
    `  static const double radius = ${radius};`,
    '',
    `  static const String fontDisplay = '${must(font, 'display', 'font')}';`,
    `  static const String fontBody = '${must(font, 'body', 'font')}';`,
    '}',
    '',
    '/// NIKATRU brand tokens - dark palette. Overrides the surface/text colors of',
    '/// [NikatruTokens]; tokens that do not change in dark mode are re-exported',
    '/// so either class can be used on its own.',
    'class NikatruTokensDark {',
    '  NikatruTokensDark._();',
    '',
  );
  for (const name of DARK_COLORS) {
    lines.push(`  static const Color ${dartIdent(name)} = ${dartColor(must(dark, name, 'dark'))};`);
  }
  lines.push('');
  for (const name of LIGHT_COLORS.filter((n) => !DARK_COLORS.includes(n))) {
    lines.push(`  static const Color ${dartIdent(name)} = NikatruTokens.${dartIdent(name)};`);
  }
  lines.push(
    '  static const double radius = NikatruTokens.radius;',
    '  static const String fontDisplay = NikatruTokens.fontDisplay;',
    '  static const String fontBody = NikatruTokens.fontBody;',
    '}',
  );
  return lines.join('\n') + '\n';
}

/* ------------------------------------------------------------------ */

export default {
  source: ['tokens/**/*.json'],
  hooks: {
    formats: {
      'nikatru/css': formatCss,
      'nikatru/dart': formatDart,
    },
  },
  platforms: {
    css: {
      transforms: ['name/kebab'],
      buildPath: 'build/',
      files: [{ destination: 'tokens.css', format: 'nikatru/css' }],
    },
    dart: {
      transforms: ['name/kebab'],
      buildPath: 'build/',
      files: [{ destination: 'nikatru_tokens.dart', format: 'nikatru/dart' }],
    },
  },
};
